# Generated by Django 3.0.6 on 2020-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('ans', models.TextField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
